[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "netlify-plugin-cache-nextjs"
